### ISSUE TITLE
Level Settings - Verbesserungen und Fehler

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#1]
- Levelname ohne Anfangsziffer
- Überschrift fett/größer
- Beschreibung klein
- Angabe Hintergrund: Textur oder Farbe

**Comment by anhalter42** [comment]
wo meinst du die ersten 3 dinge? im pause menu? oder beim Level auswählen?
Mit Hintergrund meinst du den Grund, also ausserhalb des Labyrinths?

**Comment by Spielername** [comment]
Die ersten 3 Punkte sind bezogen auf die Levelauswahl im Spiel.
#Tutorial 1
//Ganz einfach geht es los
...
![unity_level](https://cloud.githubusercontent.com/assets/1715755/12192263/5a0b0dfe-b5dd-11e5-9c94-20fed30993b0.JPG)

Mit Hintergrund meine ich wirklich den Grund ausserhalb des Labyrinths.

Hatte gestern erstmal nur meine Notizen rein kopiert. Die Tage danach hätte ich sowieso alles genauer beschrieben.

**Comment by anhalter42** [comment]
- groundColor in LevelSettings hinzugefügt
- Level Auswahl UI überarbeitet
