### ISSUE TITLE
Script: Variation

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#10]
Beim Modus "Deactivate/Activate Some", scheint die Wahrscheinlichkeit keine Rolle zu spielen.
Wie im Beispiel zu sehen, ist die Wahrscheinlichkeit auf 1% gesetzt, aber von 10 Stück sind 6 Stück deaktiviert. Bei der hinteren Mauer ist es noch deutlicher, denn da fehlt alles.

![break_wall_variantion_fehler](https://cloud.githubusercontent.com/assets/1715755/13379830/a11010ec-de31-11e5-9539-aacc74d91edd.JPG)

**Comment by anhalter42** [comment]
Das Attribute Probability hat nur Auswirkung bei One oder ZeroOrOne.
Was soll es bei vielen bedeuten? Bei "vielen" wird aktuell eine zufällige Zahl im Bereich 0 bis Anzahl ermittelt und diese werden dann aktiviert/deaktiviert.
Könnte man irgendwie die Probability nutzen für die Chance auf große Zahlen ? Wie soll da die Formel aussehen?

**Comment by Spielername** [comment]
Ich stell mir diese möglichen Lösungen vor:
1. Alle Teilobjekte werden einzeln durch gegangen und für jedes wird entschieden ob es sichtbar ist oder nicht.
2. Man sagt an, wieviel Prozent der Teilobjekte sichtbar/unsichtbar.

**Comment by anhalter42** [comment]
Algo vor "Viele" nun:
- n = Zahl zwischen 0 und Anzahl
- wähle aus der Liste zufällig n Einträge
- für alle gewählten prüfe "ist Wahrscheinlichkeit gerade ausreichend" dann schalte
