### ISSUE TITLE
Debugging: Snapshot

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#11]
Wir benötigen eine Technik, um einen Snapshot des aktuellen Labyrinth zu erstellen. Das kann einmal als Bild und später vielleicht sogar als Level selbst sein, sobald es die Lade- und Speichertechnik gibt.

> ursp. Problem: Ein Labyrinth, welches nicht lösbar war.

**Comment by anhalter42** [comment]
Im LevelController wurde eine MazeMapTexture hinzugefügt, diese enthält ein Abbild des Maze. Ist natürlich nur ein Bild und enthält demzufolge nicht alle Informationen.

**Comment by anhalter42** [comment]
MiniMap mit Speichern ist hinzugefügt. Reicht das?

**Comment by Spielername** [comment]
Die Anzeige mit Speichermöglichkeit als Bild ist soweit erst mal ausreichend. Können den Issue schließen. Sollte es weitere Wünsche geben, machen wir das in einem neuen Issue.
