### ISSUE TITLE
Audio Bereich erweitern

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#4]
- Levelstartmusik
- Scoreerreichungsmusik

Vielleicht rein mixen oder überblenden.

**Comment by anhalter42** [comment]
audioScoreReached gibt es in CellDesc bereits.
Levelstart Musik, denke ich, sollte im LevelStartIntro rein was es ja noch nicht gibt ;-)

**Comment by anhalter42** [comment]
neue Settings in CellDesc und Level:
    audioBackgroundLevelStart
    audioBackgroundLevelExitOpen
