### ISSUE TITLE
CellDescs Props array

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#5]
### Beschreibung:

Die Angabe mehrerer Props mit gleichen Wahrscheinlichkeiten, für eine bessere Lesbarkeit der CellDesc. 
### Beispiel:

leftProps       Prop_Crates1_R-;3
leftProps       Prop_Crates2_R-;3
leftProps       Prop_Crates3_R-;3
### Wunsch:

leftProps:      Prop_Crates1_R-,Prop_Crates2_R-,Prop_Crates3_R;3

**Comment by anhalter42** [comment]
ist drin
