### ISSUE TITLE
Zellanordnungen

### ISSUE THREAD

**Issue by Spielername** [anhalter42/Lobster#9]
Das Tagsystem ist eine gute Möglichkeit eine Zelle grob zu bestücken.Allerdings wird das Tagsystem bei größeren Zellen nicht mehr ausreichen. Hier stelle ich mir eine automatischen Objekt Kollisionserkennung vor, welche beim bestücken der Zelle ineinander liegende Objekte entfernt. Eventuell durch die Angabe von Prioritäten noch beeinflussbar.

**Comment by anhalter42** [comment]
Es ist nun möglich mit der Component PrefabConditions und Attribute checkMeshBounds über Bounding Boxen prüfen zu lassen ob das Objekt reinpasst. 
Prios gibts noch nicht... da müsste man an anderer Stelle was machen
